modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="create_nomad"
version="0.1.3"
displayName="Nomad"
displayURL="https://github.com/dcchill/gearbound"
logoFile="logo.png"
credits="Dcchill"
authors="Dcchill"
description="Adds more gadgets and storage to the create mod"
enumExtensions="META-INF/enumextensions.json"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.create_nomad]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.create_nomad]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.create_nomad]]
    modId="create"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_nomad]]
    modId="curios_api"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_nomad]]
    modId="geckolib"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_nomad]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration